{% set name = "PanelAero" %}
{% set version = "2025.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PanelAero-{{ version }}.tar.gz
  sha256: 4e91b3f20648e98317320dc5e8c6d9eb0bcc708e970f021c9736813f8a14e433

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - panelaero
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DLR-AE/PanelAero
  summary: An Implementation of the Vortex Lattice and the Doublet Lattice Method.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ArneVoss
